apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.configMap.name }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
data:
  APP_VERSION: {{ .Chart.Version }}
  ENVIRONMENT: {{ .Values.environment }}