# Default values for node projects.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: desyco/vidbid-plutus
  tag: 0.0.1
  pullPolicy: Always
service:
  name: vidbid-plutus
  type: ClusterIP
  externalPort: 80
  internalPort: 9080
  annotations:
    fabric8.io/expose: "true"
    fabric8.io/ingress.annotations: "kubernetes.io/ingress.class: nginx"
resources:
  limits:
    cpu: 200m
    memory: 128Mi
  requests:
    cpu: 200m
    memory: 128Mi
probePath: /api/healthcheck
livenessProbe:
  initialDelaySeconds: 60
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
readinessProbe:
  periodSeconds: 10
  successThreshold: 1
  timeoutSeconds: 1
terminationGracePeriodSeconds: 10

# Custom values
configMap:
  name: vidbid-plutus-config-map
environment: test

node:
  imageTag: 1.32.1
  resources:
      limits:
        cpu: "1"
        memory: 4Gi
      requests:
        cpu: "0.5"
        memory: 2Gi
  dbStorage: 16Gi
  dbStorageClass: standard
  ipcStorage: 1Gi
  ipcStorageClass: standard

wallet:
  imageTag: 2021.12.15
  resources:
      limits:
        cpu: 400m
        memory: 512Mi
      requests:
        cpu: 200m
        memory: 256Mi
  dbStorage: 512Mi
  dbStorageClass: standard